// =============================================================
// DISC — Glosario de las palabras del test
// Definiciones cortas (español rioplatense) para las 89 palabras
// únicas de WORD_GROUPS. Se muestran a demanda en el cuestionario
// para quien no conoce un término (ej. "Ecuánime").
// Las claves deben coincidir EXACTO con las palabras de disc-evaluator.
// =============================================================

export const WORD_DEFINITIONS: Record<string, string> = {
  Adaptable: "Se ajusta con facilidad a nuevas situaciones.",
  Alentador: "Da ánimo y motiva a los demás.",
  Ameno: "Agradable y fácil de tratar.",
  Amigable: "Cordial, busca el buen trato.",
  Amistoso: "Cercano y de trato afectuoso.",
  "Analítico": "Examina todo en detalle antes de concluir.",
  Animado: "Lleno de energía y entusiasmo.",
  Apacible: "Tranquilo, de carácter sereno.",
  "Apegado a normas": "Respeta las reglas y los procedimientos.",
  Atento: "Cortés y pendiente de los demás.",
  Atrevido: "Se anima a tomar riesgos.",
  Audaz: "Valiente para encarar desafíos.",
  Autosuficiente: "Se basta a sí mismo, no depende de otros.",
  Bondadoso: "De buen corazón, ayuda a los demás.",
  Calmado: "Sereno, no se altera fácilmente.",
  Cauteloso: "Actúa con prudencia y cuidado.",
  Cautivador: "Atrae y encanta a la gente.",
  Certero: "Acierta; preciso en lo que dice o hace.",
  Colaborador: "Trabaja bien en equipo y aporta a otros.",
  Comedido: "Moderado y respetuoso al actuar.",
  Compasivo: "Se conmueve y ayuda ante el dolor ajeno.",
  Competitivo: "Busca ganar y superarse.",
  Complaciente: "Tiende a satisfacer a los demás.",
  Comunicativo: "Se expresa con facilidad y habla mucho.",
  Concienzudo: "Hace las cosas con esmero y detalle.",
  Considerado: "Tiene en cuenta a los demás.",
  Constante: "Sostiene el esfuerzo sin aflojar.",
  Controlado: "Domina sus impulsos y emociones.",
  Cuidadoso: "Hace todo con atención para no errar.",
  Decidido: "Resuelve y actúa sin dudar.",
  Decisivo: "Toma decisiones con firmeza.",
  "Diplomático": "Maneja los conflictos con tacto.",
  Directivo: "Toma el mando y da indicaciones.",
  Directo: "Va al grano, dice las cosas de frente.",
  Discerniente: "Distingue bien lo importante de lo que no.",
  Discreto: "Reservado, no llama la atención.",
  Dominante: "Tiende a imponerse y a liderar.",
  "Ecuánime": "Justo y equilibrado al juzgar.",
  Encantador: "Cae bien y agrada con naturalidad.",
  "Enérgico": "Lleno de fuerza y vitalidad.",
  Entusiasta: "Se apasiona y contagia ganas.",
  "Espontáneo": "Actúa con naturalidad, sin planearlo.",
  Estable: "Constante y predecible.",
  Estimulante: "Inspira y motiva a otros.",
  Evaluador: "Analiza y juzga con criterio.",
  Exigente: "Pide alto nivel a sí mismo y a otros.",
  Expresivo: "Muestra abiertamente lo que siente.",
  Extrovertido: "Sociable, disfruta del contacto con la gente.",
  Firme: "Sostiene su postura con seguridad.",
  Franco: "Sincero, dice lo que piensa.",
  Generoso: "Da y comparte con los demás.",
  Gentil: "Amable y delicado en el trato.",
  Impulsivo: "Actúa por instinto, sin pensarlo mucho.",
  Independiente: "Se maneja por su cuenta.",
  Ingenioso: "Resuelve con creatividad e ideas.",
  Inquieto: "Activo, le cuesta quedarse quieto.",
  Inspirador: "Motiva a otros con su ejemplo.",
  Investigador: "Indaga y busca entender a fondo.",
  Jovial: "Alegre y de buen humor.",
  Leal: "Fiel y comprometido con los suyos.",
  "Lógico": "Razona de forma ordenada y racional.",
  Meticuloso: "Cuida cada detalle con precisión.",
  "Metódico": "Trabaja con orden y sistema.",
  Moderado: "Mesurado, sin excesos.",
  Ordenado: "Mantiene todo en su lugar.",
  Osado: "Se anima a lo arriesgado.",
  Paciente: "Espera y tolera sin frustrarse.",
  "Pacífico": "Evita el conflicto, busca la paz.",
  Perceptivo: "Capta y nota lo que otros no ven.",
  Perfeccionista: "Busca que todo quede impecable.",
  Persistente: "No abandona; insiste hasta lograrlo.",
  Persuasivo: "Convence con facilidad.",
  Pionero: "Abre camino; va primero a lo nuevo.",
  Popular: "Querido y conocido por muchos.",
  Precavido: "Previene y se anticipa a los problemas.",
  Preciso: "Exacto, sin errores.",
  Promotor: "Impulsa ideas y proyectos.",
  Prudente: "Actúa con cuidado y sensatez.",
  Receptivo: "Abierto a escuchar y recibir ideas.",
  Reflexivo: "Piensa bien antes de actuar.",
  Resuelto: "Decidido y seguro al actuar.",
  Satisfecho: "Conforme con lo que tiene.",
  Servicial: "Siempre dispuesto a ayudar.",
  "Sistemático": "Sigue un orden y un método claro.",
  Sociable: "Disfruta y busca el trato con la gente.",
  Tolerante: "Acepta y respeta las diferencias.",
  Tranquilo: "Sereno, sin sobresaltos.",
  Valiente: "Enfrenta el miedo y los desafíos.",
  Vigoroso: "Con mucha fuerza y energía.",
};

// Devuelve la definición de una palabra del test (o null si no hay).
export function wordDefinition(word: string): string | null {
  return WORD_DEFINITIONS[word] ?? null;
}
